### PR TITLE
github-style syntax highlighting

### PR DESCRIPTION
**Pull request by bravelittlescientist**
Adds syntax-highlighting to the codeblocks, as suggested by @jirwin.

PR updates to use jekyll-style syntax-highlighting, using pygments default css file.

### CODE REVIEW

**Comment by jirwin** [comment]
Hrm, the rich diff on github doesn't appear to have syntax hilighting.

**Comment by robert-chiniquy** [comment]
cool +1

**Comment by eddywashere** [comment]
:+1:

**Comment by jirwin** [comment]
+1

**Pull request merged**
